import { Component, OnInit, ViewChild } from '@angular/core';
import { IonInfiniteScroll } from '@ionic/angular';

@Component({
  selector: 'app-product-summery',
  templateUrl: './product-summery.page.html',
  styleUrls: ['./product-summery.page.scss'],
})
export class ProductSummeryPage implements OnInit {
  Enable: any;
  showSearchbar: boolean = false;
  productSummeyData: any;
  sizesData: any;
  //loadData:any;

  @ViewChild(IonInfiniteScroll) infiniteScroll: IonInfiniteScroll;
 
  ngOnInit(): void {
    this.productSummeyData = [
      {
        id:"01",
        name: "DMuse",
        modal: "DMuse01",
        sku: "",
        sizesData: "",
        discription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
        current_price: "$1,260",
        old_price: "$1,799",
        img: "../../assets/images/pro1.jpg",
        wishlist: "1",
        comparison: "",
        discount: "30%",
      },
      {
        id:"02",
        name: "DMuse",
        modal: "DMuse02",
        sku: "",
        discription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
        current_price: "$1,260",
        old_price: "$1,799",
        img: "../../assets/images/pro2.jpg",
        wishlist: "1",
        comparison: "",
        discount: "30%",
      },
      {
        id:"03",
        name: "DMuse",
        modal: "DMuse03",
        sku: "",
        
        discription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
        current_price: "$1,260",
        old_price: "$1,799",
        img: "../../assets/images/pro3.jpg",
        wishlist: "0",
        comparison: "",
        discount: "30%",
      },
      {
        id:"04",
        name: "DMuse",
        modal: "DMuse04",
        sku: "",
        
        discription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
        current_price: "$1,260",
        old_price: "$1,799",
        img: "../../assets/images/pro4.jpg",
        wishlist: "0",
        comparison: "",
        discount: "30%",
      },
      {
        id:"01",
        name: "DMuse",
        modal: "DMuse01",
        sku: "",
        
        discription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
        current_price: "$1,260",
        old_price: "$1,799",
        img: "../../assets/images/pro1.jpg",
        wishlist: "0",
        comparison: "",
        discount: "30%",
      },
      {
        id:"02",
        name: "DMuse",
        modal: "DMuse02",
        sku: "",
        
        discription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
        current_price: "$1,260",
        old_price: "$1,799",
        img: "../../assets/images/pro2.jpg",
        wishlist: "1",
        comparison: "",
        discount: "30%",
      },
      {
        id:"03",
        name: "DMuse",
        modal: "DMuse03",
        sku: "",
        
        discription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
        current_price: "$1,260",
        old_price: "$1,799",
        img: "../../assets/images/pro3.jpg",
        wishlist: "1",
        comparison: "",
        discount: "30%",
      },
      {
        id:"04",
        name: "DMuse",
        modal: "DMuse04",
        sku: "",
        
        discription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
        current_price: "$1,260",
        old_price: "$1,799",
        img: "../../assets/images/pro4.jpg",
        wishlist: "1",
        comparison: "",
        discount: "30%",
      },
      {
        id:"01",
        name: "DMuse",
        modal: "DMuse01",
        sku: "",
        
        discription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
        current_price: "$1,260",
        old_price: "$1,799",
        img: "../../assets/images/pro1.jpg",
        wishlist: "0",
        comparison: "",
        discount: "30%",
      },
      {
        id:"02",
        name: "DMuse",
        modal: "DMuse02",
        sku: "",
        
        discription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
        current_price: "$1,260",
        old_price: "$1,799",
        img: "../../assets/images/pro2.jpg",
        wishlist: "1",
        comparison: "",
        discount: "30%",
      },
      {
        id:"03",
        name: "DMuse",
        modal: "DMuse03",
        sku: "",
        
        discription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
        current_price: "$1,260",
        old_price: "$1,799",
        img: "../../assets/images/pro3.jpg",
        wishlist: "1",
        comparison: "",
        discount: "30%",
      },
      {
        id:"04",
        name: "DMuse",
        modal: "DMuse04",
        sku: "",
        
        discription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
        current_price: "$1,260",
        old_price: "$1,799",
        img: "../../assets/images/pro4.jpg",
        wishlist: "0",
        comparison: "",
        discount: "30%",
      },
      {
        id:"01",
        name: "DMuse",
        modal: "DMuse01",
        sku: "",
        
        discription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
        current_price: "$1,260",
        old_price: "$1,799",
        img: "../../assets/images/pro1.jpg",
        wishlist: "1",
        comparison: "",
        discount: "30%",
      },
      {
        id:"02",
        name: "DMuse",
        modal: "DMuse02",
        sku: "",

        discription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
        current_price: "$1,260",
        old_price: "$1,799",
        img: "../../assets/images/pro2.jpg",
        wishlist: "1",
        comparison: "",
        discount: "30%",
      },
      {
        id:"03",
        name: "DMuse",
        modal: "DMuse03",
        sku: "",
        discription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
        current_price: "$1,260",
        old_price: "$1,799",
        img: "../../assets/images/pro3.jpg",
        wishlist: "1",
        comparison: "",
        discount: "30%",
      },
      {
        id:"04",
        name: "DMuse",
        modal: "DMuse04",
        sku: "",
        discription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
        current_price: "$1,260",
        old_price: "$1,799",
        img: "../../assets/images/pro4.jpg",
        wishlist: "1",
        comparison: "",
        discount: "30%",
      },
      {
        id:"01",
        name: "DMuse",
        modal: "DMuse01",
        sku: "",
        discription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
        current_price: "$1,260",
        old_price: "$1,799",
        img: "../../assets/images/pro1.jpg",
        wishlist: "1",
        comparison: "",
        discount: "30%",
      },
      {
        id:"02",
        name: "DMuse",
        modal: "DMuse02",
        sku: "",
        discription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
        current_price: "$1,260",
        old_price: "$1,799",
        img: "../../assets/images/pro2.jpg",
        wishlist: "1",
        comparison: "",
        discount: "30%",
      },
      {
        id:"03",
        name: "DMuse",
        modal: "DMuse03",
        sku: "",
        discription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
        current_price: "$1,260",
        old_price: "$1,799",
        img: "../../assets/images/pro3.jpg",
        wishlist: "1",
        comparison: "",
        discount: "30%",
      },
      {
        id:"04",
        name: "DMuse",
        modal: "DMuse04",
        sku: "",
        discription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
        current_price: "$1,260",
        old_price: "$1,799",
        img: "../../assets/images/pro4.jpg",
        wishlist: "1",
        comparison: "",
        discount: "30%",
      },
    ]
  }


toggleSearchbar() {
    this.showSearchbar = !this.showSearchbar;
}


}
